sudo: required
group: edge

services:
  - docker

language: bash

env:
  - REPO=jcalderonzumba/chrome-headless-browser DIR=chrome
  - REPO=jcalderonzumba/chrome-headless-browser-selenium DIR=chromedriver

before_install:
  - export VERSION0=`docker run --name chrome --rm --entrypoint=/usr/bin/google-chrome-unstable $REPO --version | grep -Po '(?<=Google Chrome )[^ ]+'`
  - wget https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb
  - docker build -t $REPO $DIR

script:
  - export VERSION1=`docker run --name chrome --rm --entrypoint=/usr/bin/google-chrome-unstable $REPO --version | grep -Po '(?<=Google Chrome )[^ ]+'`
  - docker tag $REPO $REPO:latest
  - docker tag $REPO $REPO:$VERSION1
  - docker run --init -it --rm --name chrome --cap-add=SYS_ADMIN --entrypoint=/usr/bin/google-chrome-unstable $REPO:latest   --headless --disable-dev-shm-usage --disable-gpu --dump-dom http://info.cern.ch/hypertext/WWW/TheProject.html

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$VERSION0" != "$VERSION1" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $REPO;
    fi
